FROM golang:1.20

WORKDIR /src/
COPY . .
RUN apt-get update && apt-get install -y librdkafka-dev
RUN go mod download
RUN mkdir /app
RUN go build -o /app/walletcore ./cmd/walletcore/main.go
RUN chmod a+x /app/walletcore

EXPOSE 8080

CMD ["/app/walletcore"]