version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports: 
      - "8080:80"
    networks: 
      - desafio-2

  app:
    image: thiagozeyu/node-fullcycle
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    restart: always
    volumes: 
      - ./node:/usr/src/app
    depends_on: 
       - db
    networks: 
      - desafio-2

  db: 
    image: mysql:5.7
    # command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=fullcycle
      - MYSQL_ROOT_PASSWORD=minhasupersenharoots
    volumes:
      - ./node/init.sql:/docker-entrypoint-initdb.d/init.sql
    #command: --init-file /docker-entrypoint-initdb.d/init.sql
    networks: 
      - desafio-2

networks: 
  desafio-2:
    driver: bridge